### ISSUE TITLE
Question about extracting tools

### ISSUE THREAD

**Issue by Spphire** [MilkyLan/AzurLane-Live2d#1]
Thanks for sharing! How did you extract Live2D files? Did you use this tool: "https://github.com/Perfare/AzurLaneLive2DExtract" ?.
Recently, the 7th anniversary of Azurlane, I tried to use this tool to export live2d but failed, maybe the file was encrypted?

**Comment by MilkyLan** [comment]
You can use this tools:https://github.com/aelurum/AssetStudio
